### ISSUE TITLE
Format of `nix-package-url`?

### ISSUE THREAD

**Issue by Mr-Andersen** [DeterminateSystems/nix-installer-action#106]
So, I'd like to use specific version of Nix on my CI. I guess this should be solved with `nix-package-url`. But what kind of data should be hosted at this URL? Pre-built Nix? Are built Nix versions hosted anywhere?

**Comment by Montmorency** [comment]
Also trying out DetSystems github action installer and I'm a little confused by what nix-package-url should refer to? e.g. on the cachix nix installer action you specify nix_path to target a particule revision of nixpkgs is nix-package-url intended to be the same thing?:
e.g.
```
      - name: Install nix and cachix
        uses: cachix/install-nix-action@v27
        with:
           nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/38da06c69f821af50323d54b28d342cc3eb42891.tar.gz
      ```
    I checked upstream in the installer itself but still a little unclear what nix-package-url refers to e.g. a version of nix or a nixpkgs etc?
