### ISSUE TITLE
`experimental-features` is not considered but `extra-experimental-features` is?

### ISSUE THREAD

**Issue by FRidh** [DeterminateSystems/nix-installer-action#28]
I noticed that setting `experimental-features` in `extra-conf` has no effect, however, setting `extra-experimental-features` does. Is this expected behaviour? Could this be because by default it is set to include flakes?

```yml
name: "CI using nix"

on:
    push:
      branches:
        - develop
        - main

    pull_request:
      branches:
        - develop
        - main

jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - uses: DeterminateSystems/nix-installer-action@main
          with:
            extra-conf: |
              extra-experimental-features = nix-command flakes impure-derivations ca-derivations
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - run: nix flake check
```

**Comment by FRidh** [comment]
Even more interesting. One run with `extra-experimental-features` succeeded (when I made a PR), and another run (post-merge) running the exact same job failed again with
```sh
error: experimental Nix feature 'impure-derivations' is disabled; use '--extra-experimental-features impure-derivations' to override
(use '--show-trace' to show detailed location information)
Error: Process completed with exit code 1.
```
So it is not just `experimental-features` but also `extra-experimental-features` that is not (always) considered.

**Comment by Hoverbear** [comment]
@cole-h and I confirmed this is fixed on our `main` branch and we were planning to make a new release, so hopefully this will be fixed with that! Expect by Friday it will be fixed.

**Comment by FRidh** [comment]
> Is this some goofy yaml thing???

The horror called yaml!

Thank you for looking into this.

**Comment by FRidh** [comment]
Using the override to 0.10.0 for now. 

```
name: "CI using nix"

on:
    push:
      branches:
        - develop
        - main

    pull_request:
      branches:
        - develop
        - main

jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - uses: DeterminateSystems/nix-installer-action@main
          with:
            nix-installer-tag: v0.10.0
            extra-conf: |
              extra-experimental-features = nix-command flakes impure-derivations ca-derivations
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - run: nix flake check
```
