### ISSUE TITLE
Proposal: default github-token to github.token

### ISSUE THREAD

**Issue by EricCrosson** [DeterminateSystems/nix-installer-action#3]
Howdy,

Thanks for your work on `nix-installer` and this action! I'm rooting for the success of both projects :slightly_smiling_face: 

I noticed the readme recommends supplying the `github-token` input, otherwise "you will likely get rate limited."

Have you considered defaulting `github-token` to the `github.token` value from the [github context]? This would improve the ergonomics of using the action:

```yaml
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
```

though it would change the semantics of the current implementation. I'm not sure how strongly the maintainers feel about keeping the current behavior, which makes it possible to avoid authenticated requests.

Though, one option would be to explicitly opt out of authenticated requests, maybe with an input like:

```yaml
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ""
```
or
```yaml
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        use-unauthenticated-requests: true
```

What do you think? I'm happy to open a PR if this aligns with the direction of the project.

Cheers!

[github context]: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
