### ISSUE TITLE
`init: none` also requires `planner: Linux`

### ISSUE THREAD

**Issue by maralorn** [DeterminateSystems/nix-installer-action#33]
I am trying to use the action on a gitea-runner. The docker image is `catthehacker/ubuntu:act-latest`.

My job description is simple:
```
name: Nix build
on: [push]
run-name: Test and build flake
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@v4
        with:
          init: none
```
You can see the result here: https://code.maralorn.de/maralorn/runner-test/actions/runs/17/jobs/0

For your convenience the error message is:
```
info: downloading installer (https://install.determinate.systems/nix/tag/v0.10.0/nix-installer-x86_64-linux)
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Could not detect systemd; you may be able to get up and running without systemd with `nix-installer install linux --init none`.
      See https://github.com/DeterminateSystems/nix-installer#without-systemd-linux-only for documentation on usage and drawbacks.
location:
   src/cli/subcommand/install.rs:193
backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

This is surprising because before that it says:
```
Set NIX_INSTALLER_INIT=none
```

I might be holding it wrong. Please enlighten me!
