### ISSUE TITLE
 error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted

### ISSUE THREAD

**Issue by likwid** [DeterminateSystems/nix-installer-action#57]
I am getting this error while using the nix installer action. I am really mystified by what is happening, because I am using this action in two different repositories. In one repository the action works fine, and I don't have any issues. In another repository I am getting the issue title as an error.

Here is the github action workflow yaml.  I am sure this will be confusing, but I am on GitHub Enterprise Server, and my work has strict rules around which actions we use. I am using [GitHub Actions Sync](https://github.com/actions/actions-sync) to bring public actions into GHES. 

```yaml
- name: Install Nix
   uses: redacted-actions/nix-installer-action@main
   with:
     init: none
     planner: linux
     
- uses: redacted-actions/magic-nix-cache-action@main

- name: Get all changed and modified yaml files
  id: changed_files
  uses: redacted-actions/changed-files@v38
  with:
    files: |
      **/*.yml
      **/*.yaml
    separator: " "

- name: Run yamllint
  run: |
    nix develop --command yamllint -c .yamllint.yaml ${{ steps.changed_files.outputs.all_changed_files }}
``` 

The workflow fails on the Run yamllint step, and throws the error `error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted`

In the repository where things work, I am using a pretty similar invocation, but without the usage of `nix develop`. I added a test nix develop invocation, and that also fails with `error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted`.

Any idea what could be going on?
